/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto_fernandoherrera;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author herre
 */
public class Alquiler_Vehiculos extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel ();
    ArrayList<RegistroGUI> listado = new ArrayList<RegistroGUI>();
    
    public Alquiler_Vehiculos() {
        initComponents();
        this.setTitle("REGISTRO DE ALQUILER");
        this.setSize(790, 630);
        this.setLocationRelativeTo(null);
        modelo.addColumn("NOMBRE");
        modelo.addColumn("EDAD");
        modelo.addColumn("MOTIVO");
        modelo.addColumn("TIPO DE AUTO");
        modelo.addColumn("MARCA DE AUTO");
        modelo.addColumn("DIAS DE ALQUILER");
        refrescarTabla();
    }
    
    /**
     *
     */
    public final void refrescarTabla(){
        while (modelo.getRowCount()>0){
            modelo.removeRow(0);
        }
        
        for (RegistroGUI registro : listado) {
            Object r[] = new Object[6];
            r[0] = registro.getNombre();
            r[1] = registro.getEdad();
            r[2] = registro.getMotivo();
            r[3] = registro.getTipo_auto();
            r[4] = registro.getMarca_auto();
            r[5] = registro.getDia_alquiler();
            
            modelo.addRow(r);
            
        }
        
        tblRegistroAlquiler.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRegistroAlquiler = new javax.swing.JTable();
        nombreUsuario = new javax.swing.JLabel();
        edadUsuario = new javax.swing.JLabel();
        intDiaAlquiler = new javax.swing.JTextField();
        txtMotivoUsuario = new javax.swing.JComboBox<>();
        motivoUsuario = new javax.swing.JLabel();
        diaAlquiler = new javax.swing.JLabel();
        txtNombreUsuario1 = new javax.swing.JTextField();
        marcaAlquiler = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        tipoAlquiler = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        btnBorrarAlquiler = new javax.swing.JButton();
        btnAgregarAlquiler = new javax.swing.JButton();
        intEdadUsuario1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblRegistroAlquiler.setFont(new java.awt.Font("MS UI Gothic", 0, 14)); // NOI18N
        tblRegistroAlquiler.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblRegistroAlquiler);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 215, 760, 250));

        nombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        nombreUsuario.setText("Nombre");
        jPanel1.add(nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 60, -1));

        edadUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        edadUsuario.setText("Edad");
        jPanel1.add(edadUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 40, -1));
        jPanel1.add(intDiaAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 90, 50, 30));

        txtMotivoUsuario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Viaje Familiar", "Turismo", "Trabajo", "Otro" }));
        txtMotivoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotivoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtMotivoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 92, -1, 30));

        motivoUsuario.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        motivoUsuario.setText("Motivo");
        jPanel1.add(motivoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 50, -1));

        diaAlquiler.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        diaAlquiler.setText("Dias de Alquiler: ");
        jPanel1.add(diaAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 120, -1));
        jPanel1.add(txtNombreUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 200, 30));

        marcaAlquiler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "KIA", "TOYOTA", "NISSAN", "VOLKSWAGEN", "MITSUBISHI", "CHEVROLET" }));
        jPanel1.add(marcaAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 140, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tipo de Auto");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 90, -1));

        tipoAlquiler.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "SEDAN", "SUV", "PICKUP", "VAN" }));
        jPanel1.add(tipoAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 140, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Marca de Auto");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 50, 100, -1));

        btnBorrarAlquiler.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBorrarAlquiler.setText("Borrar");
        btnBorrarAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarAlquilerActionPerformed(evt);
            }
        });
        jPanel1.add(btnBorrarAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 90, 60));

        btnAgregarAlquiler.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgregarAlquiler.setText("Agregar");
        btnAgregarAlquiler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAlquilerActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregarAlquiler, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 90, 60));
        jPanel1.add(intEdadUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 772, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBorrarAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarAlquilerActionPerformed
        txtNombreUsuario1.setText("");
        intEdadUsuario1.setText("");
        txtMotivoUsuario.setSelectedIndex(0);
        tipoAlquiler.setSelectedIndex(0);
        marcaAlquiler.setSelectedIndex(0);
        intDiaAlquiler.setText("");
    }//GEN-LAST:event_btnBorrarAlquilerActionPerformed

    private void btnAgregarAlquilerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAlquilerActionPerformed
        try {
            RegistroGUI registro = new RegistroGUI();
            registro.setNombre(txtNombreUsuario1.getText());
            registro.setEdad(Integer.parseInt(intDiaAlquiler.getText()));
            registro.setMotivo(txtMotivoUsuario.getSelectedItem().toString());
            registro.setTipo_auto(tipoAlquiler.getSelectedItem().toString());
            registro.setMarca_auto(marcaAlquiler.getSelectedItem().toString());
            registro.setDia_alquiler(Integer.parseInt(intDiaAlquiler.getText()));
            listado.add(registro);
            refrescarTabla();
        } catch (Exception e){
            JOptionPane.showMessageDialog(this,"ERROR AL AGREGAR EL REGISTRO");
        }
    }//GEN-LAST:event_btnAgregarAlquilerActionPerformed

    private void txtMotivoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotivoUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotivoUsuarioActionPerformed

    /*
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alquiler_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alquiler_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alquiler_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alquiler_Vehiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Alquiler_Vehiculos().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAlquiler;
    private javax.swing.JButton btnBorrarAlquiler;
    private javax.swing.JLabel diaAlquiler;
    private javax.swing.JLabel edadUsuario;
    private javax.swing.JTextField intDiaAlquiler;
    private javax.swing.JTextField intEdadUsuario1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> marcaAlquiler;
    private javax.swing.JLabel motivoUsuario;
    private javax.swing.JLabel nombreUsuario;
    private javax.swing.JTable tblRegistroAlquiler;
    private javax.swing.JComboBox<String> tipoAlquiler;
    private javax.swing.JComboBox<String> txtMotivoUsuario;
    private javax.swing.JTextField txtNombreUsuario1;
    // End of variables declaration//GEN-END:variables
}
